version: '3'
services:
  algorithm:
    image: jupyter/datascience-notebook
    ports:
      - '8888:8888'
    volumes:
      - ./data:/home/jovyan/work
    stdin_open: true
    tty: true
    container_name: algorithm
    user: root
    environment:
      - GRANT_SUDO=yes