version: '3'
services:
  node-react:
    image: node:16-alpine
    ports:
      - 3200:3000
    volumes:
      - ./workspace:/home/workspace
    stdin_open: true
    tty: true
    container_name: node-container
    environment:
      - WDS_SOCKET_PORT=0